apiVersion: v1
kind: Service
metadata:
  name: service-pgadmin
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
      nodePort: 30050
