apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    env: prod
  namespace: icgroup
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:10
        name: postgres
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bdd-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgresdb-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresdb-storage
        hostPath:
          path: /data_k8s/postgresql
